spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: abhishek@SQL
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

jwt:
  secret: kpb0zT4O/G91fyH3VVdlZqqVcgW4pVXErrI4Jmk02Io=